site_name: UQregressors

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - mdx_math

theme:
  name: material
  icon: 
    admonition: 
      warning: material/alert

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["../src"]

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Examples: examples.md
  - API Reference:
      - Bayesian:
        - Deep Ensembles: api/Bayesian/deep_ens.md
        - Dropout: api/Bayesian/dropout.md 
        - Gaussian Processes: api/Bayesian/gp.md 
        - Gaussian Process (Black Box Matrix-Matrix Inference): api/Bayesian/bbmm_gp.md
      - Conformal: 
        - Conformal Quantile Regression: api/Conformal/cqr.md 
        - K-Fold Conformal Quantile Regression: api/Conformal/k_fold_cqr.md 
        - Normalized Conformal Ensemble: api/Conformal/conformal_ens.md
      - Metrics: api/metrics.md
      - Tuning: api/tuning.md
      - Plotting: api/plotting.md
      - Utils: 
        - Activations: api/Utils/activations.md
        - Data Loader: api/Utils/data_loader.md
        - File Manager: api/Utils/file_manager.md
        - Logging: api/Utils/logging.md 
        - Torch Sklearn Utils: api/Utils/torch_sklearn_utils.md
